"""initial schema

Revision ID: ea25d4c5f272
Revises:
Create Date: 2026-06-07 22:45:46.812330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea25d4c5f272'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('difficulties',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('era', sa.Text(), server_default='', nullable=False),
    sa.Column('setting', sa.Text(), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('min_players', sa.Integer(), server_default='6', nullable=False),
    sa.Column('max_players', sa.Integer(), server_default='16', nullable=False),
    sa.Column('difficulty', sa.Text(), server_default='Medium', nullable=False),
    sa.Column('duration', sa.Text(), server_default='3-4 hours', nullable=False),
    sa.Column('theme', sa.Text(), server_default='', nullable=False),
    sa.Column('victim', sa.Text(), server_default='', nullable=False),
    sa.Column('murder_method', sa.Text(), server_default='', nullable=False),
    sa.Column('cover_image', sa.Text(), server_default='🎭', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('themes',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('era', sa.Text(), server_default='', nullable=False),
    sa.Column('icon', sa.Text(), server_default='🎭', nullable=False),
    sa.Column('setting', sa.Text(), nullable=False),
    sa.Column('icon_image_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tones',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tones')
    op.drop_table('themes')
    op.drop_table('settings')
    op.drop_table('scenarios')
    op.drop_table('difficulties')
    # ### end Alembic commands ###
